spring:
  application:
    name: spring-boot-rest-api
  mvc:
    apiversion:
      supported: 1.0,2.0
      default: 1.0

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${CONTEXT_PATH:/spring-boot-rest-api}